// user content reactions
export const FETCH_USER_CON_REACTION_BEGIN = 'FETCH_USER_CON_REACTION_BEGIN';
export const FETCH_USER_CON_REACTION_SUCCESS = 'FETCH_USER_CON_REACTION_SUCCESS';
export const FETCH_USER_CON_REACTION_FAILURE = 'FETCH_USER_CON_REACTION_FAILURE';

// reactions
export const FETCH_REACTIONS_BEGIN = 'FETCH_REACTIONS_BEGIN';
export const FETCH_REACTIONS_SUCCESS = 'FETCH_REACTIONS_SUCCESS';
export const FETCH_REACTIONS_FAILURE = 'FETCH_REACTIONS_FAILURE';

// add and delete user reactions
export const ADD_USER_CON_REACTION = 'ADD_USER_CON_REACTION';
export const DELETE_USER_CON_REACTION = 'DELETE_USER_CON_REACTION';
